name: dart lint
on:
  pull_request:

env: 
  flutter-version: '3.35.2'

jobs:
  dart-lint:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.flutter_version }}
      
      - name: Install dependencies
        run: flutter pub get

      - name: Generate files
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run Dart Lint
        run: flutter analyze  
      
      - name: Run tests
        run: flutter test


